apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  template:
    metadata:
      labels:
        app: postgres-master
        tier: backend
    spec:
      containers:
        - name: postgres-master
          image: postgres:9.6.2
          args: ["-c","listen_addresses=0.0.0.0"]
          readinessProbe:
            exec:
              command: ["psql", "-U", "postgres", "-c", "SELECT 1"]
            initialDelaySeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-U", "postgres", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
          ports:
            - containerPort: 5432
          env:  # TODO: Use configmap/secrets
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "myapp"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
